<?php

/**
 * @file
 * Contains corporate.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function corporate_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the corporate module.
    case 'help.page.corporate':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module for Corporate Advisory Board Content Type') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function corporate_theme() {
  return [
    'corporate' => [
      'render element' => 'children',
    ],
  ];
}
