<?php

/**
 * @file
 * Contains sig.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function sig_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the sig module.
    case 'help.page.sig':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module for Special Interest Groups Content Type') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function sig_theme() {
  return [
    'sig' => [
      'render element' => 'children',
    ],
  ];
}
