<?php

/**
 * @file
 * Contains lab.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function lab_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the lab module.
    case 'help.page.lab':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module for Lab Content Tyoe') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function lab_theme() {
  return [
    'lab' => [
      'render element' => 'children',
    ],
  ];
}
